title: jhboouk
email: ""
description: >-
  Personal blog powered by GitHub Pages.
baseurl: ""
url: "https://jhboouk.github.io"
lang: ko-KR
timezone: Asia/Seoul

# GitHub Pages supported theme
theme: minima

plugins:
  - jekyll-feed

# Blog settings
show_excerpts: true
